// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Username string `form:"username" validate:"gt=0,lte=32"`
	Password string `form:"password" validate:"gt=0,lte=32"`
}

type LoginResponse struct {
	StatusCode string `json:"status_code"`
	StatusMsg  string `json:"status_msg,omitempty"`
	UserId     int64  `json:"user_id,omitempty"`
	Token      string `json:"token,omitempty"`
}

type RegisterRequest struct {
	Username string `form:"username" validate:"gt=0,lte=32"`
	Password string `form:"password" validate:"gt=0,lte=32"`
}

type RegisterResponse struct {
	StatusCode string `json:"status_code"`
	StatusMsg  string `json:"status_msg,omitempty"`
	UserId     int64  `json:"user_id"`
	Token      string `json:"token"`
}

type UserInfoRequest struct {
	UserId int64  `form:"user_id" validate:"gt=0"`
	Token  string `form:"token" validate:"gt=0"`
}

type UserInfoResponse struct {
	StatusCode string `json:"status_code"`
	StatusMsg  string `json:"status_msg,omitempty"`
	User       User   `json:"user"`
}

type User struct {
	Id            int64  `json:"id"`
	Name          string `json:"name"`
	FollowCount   int64  `json:"follow_count"`
	FollowerCount int64  `json:"follower_count"`
	IsFollow      bool   `json:"is_follow"`
}
