// Code generated by goctl. DO NOT EDIT!
// Source: videomanager.proto

package server

import (
	"context"

	"github.com/sprchu/tiktok/videomgr/rpc/internal/logic"
	"github.com/sprchu/tiktok/videomgr/rpc/internal/svc"
	"github.com/sprchu/tiktok/videomgr/rpc/types/videomanager"
)

type VideoServiceServer struct {
	svcCtx *svc.ServiceContext
	videomanager.UnimplementedVideoServiceServer
}

func NewVideoServiceServer(svcCtx *svc.ServiceContext) *VideoServiceServer {
	return &VideoServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoServiceServer) Feed(ctx context.Context, in *videomanager.FeedRequest) (*videomanager.FeedResponse, error) {
	l := logic.NewFeedLogic(ctx, s.svcCtx)
	return l.Feed(in)
}

func (s *VideoServiceServer) PublishAction(ctx context.Context, in *videomanager.PublishActionRequest) (*videomanager.PublishActionResponse, error) {
	l := logic.NewPublishActionLogic(ctx, s.svcCtx)
	return l.PublishAction(in)
}

func (s *VideoServiceServer) PublishList(ctx context.Context, in *videomanager.PublishListRequest) (*videomanager.PublishListResponse, error) {
	l := logic.NewPublishListLogic(ctx, s.svcCtx)
	return l.PublishList(in)
}
