// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	relationFieldNames          = builder.RawFieldNames(&Relation{})
	relationRows                = strings.Join(relationFieldNames, ",")
	relationRowsExpectAutoSet   = strings.Join(stringx.Remove(relationFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	relationRowsWithPlaceHolder = strings.Join(stringx.Remove(relationFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheRelationIdPrefix             = "cache:relation:id:"
	cacheRelationUserIdFollowIdPrefix = "cache:relation:userId:followId:"
)

type (
	relationModel interface {
		Insert(ctx context.Context, data *Relation) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Relation, error)
		FindOneByUserIdFollowId(ctx context.Context, userId int64, followId int64) (*Relation, error)
		Update(ctx context.Context, data *Relation) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRelationModel struct {
		sqlc.CachedConn
		table string
	}

	Relation struct {
		Id       int64 `db:"id"`
		UserId   int64 `db:"user_id"`
		FollowId int64 `db:"follow_id"`
	}
)

func newRelationModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultRelationModel {
	return &defaultRelationModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`relation`",
	}
}

func (m *defaultRelationModel) Insert(ctx context.Context, data *Relation) (sql.Result, error) {
	relationIdKey := fmt.Sprintf("%s%v", cacheRelationIdPrefix, data.Id)
	relationUserIdFollowIdKey := fmt.Sprintf("%s%v:%v", cacheRelationUserIdFollowIdPrefix, data.UserId, data.FollowId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, relationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.FollowId)
	}, relationIdKey, relationUserIdFollowIdKey)
	return ret, err
}

func (m *defaultRelationModel) FindOne(ctx context.Context, id int64) (*Relation, error) {
	relationIdKey := fmt.Sprintf("%s%v", cacheRelationIdPrefix, id)
	var resp Relation
	err := m.QueryRowCtx(ctx, &resp, relationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", relationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRelationModel) FindOneByUserIdFollowId(ctx context.Context, userId int64, followId int64) (*Relation, error) {
	relationUserIdFollowIdKey := fmt.Sprintf("%s%v:%v", cacheRelationUserIdFollowIdPrefix, userId, followId)
	var resp Relation
	err := m.QueryRowIndexCtx(ctx, &resp, relationUserIdFollowIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `follow_id` = ? limit 1", relationRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, followId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRelationModel) Update(ctx context.Context, data *Relation) error {
	relationIdKey := fmt.Sprintf("%s%v", cacheRelationIdPrefix, data.Id)
	relationUserIdFollowIdKey := fmt.Sprintf("%s%v:%v", cacheRelationUserIdFollowIdPrefix, data.UserId, data.FollowId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, relationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.FollowId, data.Id)
	}, relationIdKey, relationUserIdFollowIdKey)
	return err
}

func (m *defaultRelationModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	relationIdKey := fmt.Sprintf("%s%v", cacheRelationIdPrefix, id)
	relationUserIdFollowIdKey := fmt.Sprintf("%s%v:%v", cacheRelationUserIdFollowIdPrefix, data.UserId, data.FollowId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, relationIdKey, relationUserIdFollowIdKey)
	return err
}

func (m *defaultRelationModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheRelationIdPrefix, primary)
}

func (m *defaultRelationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", relationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultRelationModel) tableName() string {
	return m.table
}
