// Code generated by goctl. DO NOT EDIT.
package types

type FollowActionRequest struct {
	Token      string `form:"token"`
	ToUserId   int64  `form:"to_user_id"`
	ActionType int32  `form:"action_type" validate:"oneof=1 2"`
}

type FollowActionResponse struct {
	StatusCode string `json:"status_code"`
	StatusMsg  string `json:"status_msg,omitempty"`
}

type FollowListRequest struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type FollowListResponse struct {
	StatusCode string `json:"status_code"`
	StatusMsg  string `json:"status_msg,omitempty"`
	UserList   []User `json:"user_list,omitempty"`
}

type FansListRequest struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type FansListResponse struct {
	StatusCode string `json:"status_code"`
	StatusMsg  string `json:"status_msg,omitempty"`
	UserList   []User `json:"user_list,omitempty"`
}

type FavoriteActionRequest struct {
	Token      string `form:"token"`
	VideoId    int64  `form:"video_id"`
	ActionType int32  `form:"action_type" validate:"oneof=1 2"`
}

type FavoriteActionResponse struct {
	StatusCode string `json:"status_code"`
	StatusMsg  string `json:"status_msg,omitempty"`
}

type FavoriteListRequest struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type FavoriteListResponse struct {
	StatusCode string  `json:"status_code"`
	StatusMsg  string  `json:"status_msg,omitempty"`
	VideoList  []Video `json:"video_list"`
}

type CommentActionRequest struct {
	UserId      int64  `form:"user_id"`
	Token       string `form:"token"`
	VideoId     int64  `form:"video_id"`
	ActionType  int32  `form:"action_type" validate:"oneof=1 2"`
	CommentText string `form:"comment_text,optional"`
	CommentId   int64  `form:"comment_id,optional"`
}

type CommentActionResponse struct {
	StatusCode string   `json:"status_code"`
	StatusMsg  string   `json:"status_msg,omitempty"`
	Comment    *Comment `json:"comment,omitempty"`
}

type CommentListRequest struct {
	Token   string `form:"token"`
	VideoId int64  `form:"video_id"`
}

type CommentListResponse struct {
	StatusCode  string    `json:"status_code"`
	StatusMsg   string    `json:"status_msg,omitempty"`
	CommentList []Comment `json:"comment_list"`
}

type Comment struct {
	Id         int64  `json:"id,omitempty"`
	User       User   `json:"user,omitempty"`
	Content    string `json:"content,omitempty"`
	CreateDate string `json:"create_date,omitempty"`
}

type User struct {
	Id            int64  `json:"id"`
	Name          string `json:"name"`
	FollowCount   int64  `json:"follow_count"`
	FollowerCount int64  `json:"follower_count"`
	IsFollow      bool   `json:"is_follow"`
}

type Video struct {
	Id            int64  `json:"id,omitempty"`
	Author        User   `json:"author,omitempty"`
	CoverUrl      string `json:"cover_url,omitempty"`
	PlayUrl       string `json:"play_url,omitempty"`
	FavoriteCount int64  `json:"favorite_count,omitempty"`
	CommentCount  int64  `json:"comment_count,omitempty"`
	IsFavorite    bool   `json:"is_favorite,omitempty"`
}
