// Code generated by goctl. DO NOT EDIT!
// Source: social.proto

package server

import (
	"context"

	"github.com/sprchu/tiktok/social/rpc/internal/logic"
	"github.com/sprchu/tiktok/social/rpc/internal/svc"
	"github.com/sprchu/tiktok/social/rpc/types/social"
)

type ServiceServer struct {
	svcCtx *svc.ServiceContext
	social.UnimplementedServiceServer
}

func NewServiceServer(svcCtx *svc.ServiceContext) *ServiceServer {
	return &ServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ServiceServer) FollowList(ctx context.Context, in *social.FollowListRequest) (*social.FollowListResponse, error) {
	l := logic.NewFollowListLogic(ctx, s.svcCtx)
	return l.FollowList(in)
}

func (s *ServiceServer) FanList(ctx context.Context, in *social.FanListRequest) (*social.FanListResponse, error) {
	l := logic.NewFanListLogic(ctx, s.svcCtx)
	return l.FanList(in)
}

func (s *ServiceServer) FollowAction(ctx context.Context, in *social.FollowActionRequest) (*social.FollowActionResponse, error) {
	l := logic.NewFollowActionLogic(ctx, s.svcCtx)
	return l.FollowAction(in)
}

func (s *ServiceServer) FavoriteAction(ctx context.Context, in *social.FavoriteActionRequest) (*social.FavoriteActionResponse, error) {
	l := logic.NewFavoriteActionLogic(ctx, s.svcCtx)
	return l.FavoriteAction(in)
}

func (s *ServiceServer) FavoriteList(ctx context.Context, in *social.FavoriteListRequest) (*social.FavoriteListResponse, error) {
	l := logic.NewFavoriteListLogic(ctx, s.svcCtx)
	return l.FavoriteList(in)
}

func (s *ServiceServer) CommentAction(ctx context.Context, in *social.CommentActionRequest) (*social.CommentActionResponse, error) {
	l := logic.NewCommentActionLogic(ctx, s.svcCtx)
	return l.CommentAction(in)
}

func (s *ServiceServer) CommentList(ctx context.Context, in *social.CommentListRequest) (*social.CommentListResponse, error) {
	l := logic.NewCommentListLogic(ctx, s.svcCtx)
	return l.CommentList(in)
}
