// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	video "github.com/ByteDance-camp/TickTalk/videomgr/api/internal/handler/video"
	"github.com/ByteDance-camp/TickTalk/videomgr/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: video.FeedHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/feed"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: video.PublishListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/action",
					Handler: video.PublishActionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/douyin/publish"),
		rest.WithMaxBytes(1 << 20 * 200),
	)
}
